export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_REQUEST_SUCCESS = "SEARCH_REQUEST_SUCCESS";
export const UPDATE_REFINEMENT_CRITERIA_REQUEST =
  "UPDATE_REFINEMENT_CRITERIA_REQUEST";
export const UPDATE_REFINEMENT_CRITERIA_SUCCESS =
  "UPDATE_REFINEMENT_CRITERIA_SUCCESS";
export const CLEAR_ALL_REFINEMENT_CRITERIA = "CLEAR_ALL_REFINEMENT_CRITERIA";

export const GET_PLAYABLE_TRANSCRIPT_REQUEST =
  "GET_PLAYABLE_TRANSCRIPT_REQUEST";
export const GET_PLAYABLE_TRANSCRIPT_SUCCESS =
  "GET_PLAYABLE_TRANSCRIPT_SUCCESS";
