export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_REQUEST_SUCCESS = "SEARCH_REQUEST_SUCCESS";
export const UPDATE_REFINEMENT_CRITERIA_REQUEST = "UPDATE_REFINEMENT_CRITERIA_REQUEST";
export const UPDATE_REFINEMENT_CRITERIA_SUCCESS = "UPDATE_REFINEMENT_CRITERIA_SUCCESS";