import delay from "./delay";

const highlights = [
  "Then you have The <span>Five</span> \r\n<span>Minute</span> <span>Journal</span>. This is often something that I will do during my writing phase – prior to \r\nworking  on  a  podcast  or  a  blog  post  or  a  book chapter  –  is  fill  out  The <span>Five</span>  <span>Minute</span> \r\n<span>Journal</span>. I’ve talked about this at length before so I’m not going to go into it.  \r\n \r\nThe next is the rishi, ginger, and turmeric tea. Those are three right offhand but I think \r\nthat less is more when it comes to consumerism.  \r\n \r\nAlright, the next set of questions. This was very interesting. You all voted these up or \r\ndown and submitted them and three questions ended up in sequence that are very, very, \r\nvery similar. So the first is: You read a lot of books; how are you able to retain all of that \r\nknowledge? This is from Jadz in London. Then the next one is: When you read books, \r\n\r\nCopyright © 2007–2018 Tim Ferriss. All Rights Reserved.  \r\n \r\n\r\n\r\n \r\n\r\nhow do you take notes? That was Mike in Newcastle, England. Then the next one is: \r\nHow do you approach the learning process to internalize long-term ideas, arguments, et \r\ncetera from a book such that it becomes part of the toolbox in your life? That is from Phil \r\nin Oklahoma. Actually there’s a fourth one, which is from Kahle, I guess, in Norway: \r\nYou read a lot of books but you’re also a very productive guy; how fast do you read and \r\nwhen do you fit reading into your day? \r\n \r\nLet me start in reverse order. How fast do I read?",
  "In any case, the <span>Five</span> <span>Minute</span> <span>Journal</span>, just buy one of these. Honestly, I have no financial \r\nstake in this and you could certainly try to replicate it yourself but having it in one bound \r\nbook is very helpful. In effect, what you’re doing is five minutes in the morning, five \r\nminutes before you go to bed. The a.m. piece is simply writing down three bullets for: I \r\nam  grateful  for…  three  things.  What  would  make  today  great;  one,  two,  three.  Daily \r\naffirmations: I am, blank, blank. \r\n \r\nAnd then at night, before you go to bed, three amazing things that happened today: one, \r\ntwo three: how could I have made today better? I have had friends reach out to me, or \r\nfans for that matter, who have listened to everything I've talked about for years and they \r\nsay this was the big game changer for them. \r\n \r\n\r\nCopyright © 2007–2018 Tim Ferriss. All Rights Reserved.",
  "Really,  his  description  of \r\njournaling got me to take my own journaling to the next level where many of you know I \r\nuse the <span>five</span>-<span>minute</span> <span>journal</span> in the morning and then as a check-in at night. But also, I’m \r\n\r\nCopyright © 2007–2018 Tim Ferriss. All Rights Reserved.  \r\n \r\n\r\n\r\n \r\n\r\ndoing more morning pages. And if you want to see what a journal entry of mine looks \r\nlike, you can just search “what my morning journal looks like”, or “morning journal” and \r\n“ferriss”, and it should pop right up on Google.  \r\n \r\nAnd there’s also a quote from Robert Rodriguez, and I believe he got this from Francis \r\nFord Coppola, and that is, “Failure is not durable.” And, I think, also from Francis Ford \r\nCoppola in the video series from Robert Rodriguez where he interviews these famous \r\ndirectors like Francis Ford Coppola, Tarantino, etc. – it’s called The Director’s Chair, it’s \r\nspectacular – one of the other quotes, I believe, from the Francis Ford Coppola episode \r\nwas, “The things that will get you fired when you’re starting out are the things they give \r\nlifetime achievement awards for later.” And I thought that was fantastic to keep in mind \r\nas you experiment and get chastised in your life. \r\n \r\nNext, Tara Brach. Famous meditation teacher, Buddhist, Dharma Talk giver – her talks \r\nare fantastic. And the lesson that I’ve learned among others from her is: Invite Mara to \r\nTea.",
  "Then I review two other journals, the <span>five</span> <span>minute</span> <span>journal</span>, which \r\npeople have heard me talk about. And then the morning pages. I go \r\nthrough and I figure things out, or try to identify things like why \r\nhaven’t  I  followed  certain  resolutions  and  followed  others.  I \r\nrealized if I looked back at, say, my resolutions for 2013 or 2014, I \r\nhad no more startups. I also had no more interviews. \r\n \r\nKevin Rose:  You were serious about this. When you say startups, do you mean \r\nstarting a startup, or you were actually talking about investing in \r\nstartups, is that right? \r\n \r\nTim Ferriss:  That’s right. I was talking about no more investing in new startups. \r\nI was able to pull the trigger on that in this last year, 2015, and \r\nwrote a long post on all of the reasons for taking a startup vacation \r\nbut why, in broader terms it’s important to say no and how to go \r\nabout  doing  it.  But  then  you  look  at  no  interviews,  no  media \r\ninterviews. I haven’t been able to stick with that. \r\n \r\n  So I'll sit down and I'll try to figure out, I know this isn’t generally \r\npleasant for me. I know it can backfire when you get misquoted. \r\nWhy do I continue to do media interviews? \r\n \r\nKevin Rose:  But it’s important for your relevance, though. You know that. \r\n\r\nCopyright © 2007–2018 Tim Ferriss. All Rights Reserved.  \r\n \r\n\r\n\r\n \r\n\r\n \r\nTim Ferriss:  But  I'm  not  convinced  it  is,  at  this  point."
];

class HighlightApi {
  static search(searchTerm) {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(Object.assign([], highlights));
      }, delay);
    });
  }
}
export default HighlightApi;
